name: .NET Core

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
  release:
    types: 
      -created

jobs:
  build_and_test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-2019]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
    - name: Build with dotnet
      run: dotnet build Scheduler/Scheduler.sln --configuration Release
    - name: Test with dotnet
      run: dotnet test Scheduler/Scheduler.sln --configuration Release
