 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     description: build project
     executor: win/default     
    
     steps:
       - checkout
       - dotnet build
       run: dotnet build Scheduler/Scheduler.sln --configuration Release
