 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     description: dotnet build
     executor: win/default

     steps:
       - checkout
       - dotnet/build:
         project: Scheduler/Scheduler.sln
         configuration: Release
