version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  test:
    description: Setup and run application tests
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Run Application Tests"
          command: dotnet.exe test -v n Scheduler/Scheduler.sln --configuration Release
      - store_test_results:
          path: /tmp/test-reports
  build:
    description: Build application with Release configuration
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Build Application according to some given configuration"
          command: dotnet.exe build Scheduler/Scheduler.sln --configuration Release
      - store_artifacts:
          path: /tmp/artifacts
          destination: build
workflows:
  test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test
